trigger:
  branches:
    include:
    - main
  paths:
    include:  
    - Services/api

variables:
- name: resourceGroup
  value: "rg-prod-boligtracker"
- name: containerRepo
  value: "boligtracker/api"
- name: containerTag
  value: "release"


pool:
  vmImage: ubuntu-latest

stages:
  - stage: BUILD
    displayName: 'Building Container Image'
    jobs:
    - job: Build
      displayName: 'Building and Pushing container image'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acrboligtracker'
          repository: $(containerRepo)
          command: 'buildAndPush'
          Dockerfile: '**/Services/api/Dockerfile'
          tags: |
            latest
            $(Build.BuildId)